# Generated by Django 2.1.7 on 2019-03-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo'),
        ),
    ]
